spring.application.name=FinancaZap

spring.datasource.url=jdbc:postgresql://localhost:5432/gerenciadorfinanca
spring.datasource.username=postgres
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update